n = input('digite algo: ')
print('O tipo primitivo desse valor é {}' .format(type(n)))
print('Só tem espaços? {}' .format(n.isspace()))
print('É um numero? {}' .format(n.isnumeric()))
print('E alfabetico? {}' .format(n.isalpha()))
print('E alfanumerico? {}' .format(n.isalnum()))
print('Esta em maiusculo? {}' .format(n.isupper()))
print('Esta em minusculo? {}' .format(n.islower()))
print('Esta capitalizada? {}' .format(n.istitle()))
